wlan_qcm6490: mdm-init: Update ctrl_interface for wpa_supplicant
This change is to update ctrl_interface to /var/run/wpa_supplicant
to from /var/run/sockets to maintain same across all targets.

Change-Id: Ie67ff92397c5faf0707fc3b73a01c1e7b3757a1a
CRs-Fixed: 3971772

diff --git a/wlan_qcm6490/wlan b/wlan_qcm6490/wlan
--- a/wlan_qcm6490/wlan
+++ b/wlan_qcm6490/wlan
@@ -81,9 +81,9 @@ do_ctrl_cld_ll () {
 
 
         cnt=0
-        while ! [ -d /var/run/sockets ]
+        while ! [ -d /var/run/wpa_supplicant ]
         do
-            echo "waiting for /var/run/sockets to mount"
+            echo "waiting for /var/run/wpa_supplicant to mount"
             sleep 1
             cnt=`expr $cnt + 1`
             if [ $cnt -ge 10 ]
@@ -92,21 +92,21 @@ do_ctrl_cld_ll () {
             fi
         done
 
-       if [ -d /var/run/sockets ]
+       if [ -d /var/run/wpa_supplicant ]
        then
-            echo "Setting permission for sockets folders" > $DUMP_TO_KMSG
-            chmod 755 /var/run/sockets
+            echo "Setting permission for wpa_supplicant folders" > $DUMP_TO_KMSG
+            chmod 755 /var/run/wpa_supplicant
             if [ $? -ne 0 ]
             then
-                echo "ERROR failed chmod of sockets" > $DUMP_TO_KMSG
+                echo "ERROR failed chmod of wpa_supplicant" > $DUMP_TO_KMSG
             fi
-            chmod 777 /var/run/sockets/wlan0
+            chmod 777 /var/run/wpa_supplicant/wlan0
             if [ $? -ne 0 ]
             then
-                echo "ERROR failed chmod of sockets/wlan0" > $DUMP_TO_KMSG
+                echo "ERROR failed chmod of wpa_supplicant/wlan0" > $DUMP_TO_KMSG
             fi
         else
-            echo "Error !! /var/run/sockets not yet available" > $DUMP_TO_KMSG
+            echo "Error !! /var/run/wpa_supplicant not yet available" > $DUMP_TO_KMSG
         fi
         ;;
 
