mdm_init: Fix issue of unable to connect to wpa_supplicant
* Start wpa_supplicant.
* Set wpa_supplicant node and containing directory proper permissions
  chmod for non-root uses to connect.
* Start udhcp client

Change-Id: I9547d39af9e7fff8b7eed026548feded658b26f9

diff --git a/wlan_sdmsteppe/wlan b/wlan_sdmsteppe/wlan
--- a/wlan_sdmsteppe/wlan
+++ b/wlan_sdmsteppe/wlan
@@ -28,6 +28,7 @@
 # IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
 export MODULE_BASE=/lib/modules/`uname -r`
+export MODULE_BASE_ALT=/usr/lib/modules/`uname -r`
 export RETRY_LIMIT=15
 HELP="Usage $0 {start | stop | restart} <ap | sta,ap>"
 DUMP_TO_KMSG=/dev/kmsg
@@ -48,7 +49,13 @@ do_ctrl_cld_ll () {
         fi
 
         set -e
-        insmod $MODULE_BASE/extra/wlan.ko $@
+        if [ -e $MODULE_BASE/extra/wlan.ko ]; then
+            insmod $MODULE_BASE/extra/wlan.ko $@
+        else
+            if [ -e $MODULE_BASE_ALT/wlan.ko ]; then
+                insmod $MODULE_BASE_ALT/wlan.ko $@
+            fi
+        fi
         set +e
 
         c=1
@@ -66,10 +73,30 @@ do_ctrl_cld_ll () {
             exit 1
         fi
 
+        echo "Starting wpa supplicant $@" > $DUMP_TO_KMSG
+        wpa_supplicant -Dnl80211 -iwlan0 -c /etc/misc/wifi/wpa_supplicant.conf -B
+
         if [ $start_ap1 -eq 1 ]; then
             echo "Adding second AP interface(wlan1)" > $DUMP_TO_KMSG
             iw dev wlan0 interface add wlan1 type __ap
             ifconfig wlan1 up 2> /dev/null
+        fi
+
+        if [ -d /var/run/wpa_supplicant ]; then
+            echo "Setting permission for wpa_supplicant folders" > $DUMP_TO_KMSG
+            chmod 755 /var/run/wpa_supplicant
+            if [ $? -ne 0 ]; then
+                echo "ERROR failed chmod of wpa_supplicant" > $DUMP_TO_KMSG
+            fi
+            chmod 777 /var/run/wpa_supplicant/wlan0
+            if [ $? -ne 0 ]; then
+                echo "ERROR failed chmod of wpa_supplicant/wlan0" > $DUMP_TO_KMSG
+            fi
+
+            echo "Starting udhcp client $@" > $DUMP_TO_KMSG
+            udhcpc -i wlan0
+        else
+            echo "Error !! /var/run/wpa_supplicant not yet available" > $DUMP_TO_KMSG
         fi
         ;;
 
